CREATE TABLE ITEM_CATEGORY (
                               ITEM_ID BIGINT REFERENCES ITEM(ID),
                               CATEGORY_ID BIGINT REFERENCES CATEGORY(ID),
                               PRIMARY KEY (ITEM_ID, CATEGORY_ID),
                               CONSTRAINT FK_ITEM_CATEGORY_ITEM FOREIGN KEY (ITEM_ID) REFERENCES ITEM(ID),
                               CONSTRAINT FK_ITEM_CATEGORY_CATEGORY FOREIGN KEY (CATEGORY_ID) REFERENCES CATEGORY(ID)
);