CREATE TABLE ROLE
(
    ID          INT PRIMARY KEY NOT NULL,
    NAME        VARCHAR(255)    NOT NULL,
    DESCRIPTION VARCHAR(255)    NOT NULL
);
---INSERT INTO ROLE (ID, NAME, DESCRIPTION)
---VALUES (1, 'admin', 'the admin role');
---INSERT INTO ROLE (ID, NAME, DESCRIPTION)
---VALUES (2, 'user', 'the user role');

