CREATE TABLE ROLE_PERMISSION
(
    ID                            INT PRIMARY KEY NOT NULL,
    ROLE_PERMISSION_ROLE_ID       INT             NOT NULL,
    CONSTRAINT FK_ROLE_PERMISSION_ROLE_ID
        FOREIGN KEY (ROLE_PERMISSION_ROLE_ID) REFERENCES
            ROLE (ID),
    ROLE_PERMISSION_PERMISSION_ID INT             NOT NULL,
    CONSTRAINT FK_ROLE_PERMISSION_PERMISSION_ID
        FOREIGN KEY (ROLE_PERMISSION_PERMISSION_ID) REFERENCES
            PERMISSION (ID)
);

---ADMIN PERMS
INSERT INTO ROLE_PERMISSION(ID, ROLE_PERMISSION_ROLE_ID, ROLE_PERMISSION_PERMISSION_ID)
VALUES (1, 1, 1);
INSERT INTO ROLE_PERMISSION(ID, ROLE_PERMISSION_ROLE_ID, ROLE_PERMISSION_PERMISSION_ID)
VALUES (2, 1, 2);
INSERT INTO ROLE_PERMISSION(ID, ROLE_PERMISSION_ROLE_ID, ROLE_PERMISSION_PERMISSION_ID)
VALUES (3, 1, 3);

---USER PERMS
INSERT INTO ROLE_PERMISSION(ID, ROLE_PERMISSION_ROLE_ID, ROLE_PERMISSION_PERMISSION_ID)
VALUES (4, 2, 1);
INSERT INTO ROLE_PERMISSION(ID, ROLE_PERMISSION_ROLE_ID, ROLE_PERMISSION_PERMISSION_ID)
VALUES (5, 2, 3);

