CREATE TABLE PERMISSION
(
    ID          INT PRIMARY KEY NOT NULL,
    NAME        VARCHAR(255)    NOT NULL,
    DESCRIPTION VARCHAR(255)    NOT NULL
);

INSERT INTO PERMISSION (ID, NAME, DESCRIPTION)
VALUES (1, 'read', 'the read perm');
INSERT INTO PERMISSION (ID, NAME, DESCRIPTION)
VALUES (2, 'write', 'the write perm');
INSERT INTO PERMISSION (ID, NAME, DESCRIPTION)
VALUES (3, 'catalog', 'the catalog perm');


